### ISSUE TITLE
Expect the data to be released.

### ISSUE THREAD

**Issue by yjh0410** [rflepp/SplitterNet-Efficient-Mobile-Denoising-Models-CVPR2024#4]
Four months have passed, and there is still no public dataset. I feel very sad.

**Comment by rflepp** [comment]
I'm very sorry it is taking so long, as my supervisor had to move machines, and the dataset is large (6TB) we were not able to host it until now in a reliable place.

**Comment by rflepp** [comment]
Here is the full released dataset: https://download.ai-benchmark.com/s/Gq3n2cS7QkH7ZMz
